appVersion: __TAG__

deployment:
  name: stationbot
  image: ghcr.io/preparingforexams/station-bot
  imagePullPolicy: IfNotPresent
  revisionHistoryLimit: 1
  replicas: 0
  labels:
    app: stationbot
  limits:
    cpu: 100m
    memory: 265Mi
  updateStrategy: Recreate

secret:
  name: station-bot

configmap:
  name: stationbot
  state:
    name: stationstate

role:
  name: stationbot
rolebinding:
  name: stationbot
serviceaccount:
  name: stationbot
