appVersion: __TAG__

deployment:
  name: stationbot
  image: ghcr.io/preparingforexams/station-bot
  imagePullPolicy: IfNotPresent
  labels:
    app: stationbot
  limits:
    cpu: 100m
    memory: 265Mi
  updateStrategy: Recreate

resources:
  limits:
    cpu: "1"
    memory: 256Mi
  requests:
    cpu: "1"
    memory: 256Mi

secret:
  name: station-bot

configmap:
  name: stationbot
  state:
    name: stationstate

role:
  name: stationbot
rolebinding:
  name: stationbot
serviceaccount:
  name: stationbot
