appVersion: __TAG__

deployment:
  name: stationbot
  image: ghcr.io/tim-hat-die-hand-an-der-maus/station-bot
  imagePullPolicy: IfNotPresent
  revisionHistoryLimit: 1
  replicas: 1
  labels:
    app: stationbot
  requests:
    cpu: 50m
    memory: 50Mi
  limits:
    cpu: 300m
    memory: 300Mi
  updateStrategy: Recreate

secret:
  name: station-bot

configmap:
  name: stationbot
  state:
    name: stationstate

role:
  name: stationbot
rolebinding:
  name: stationbot
serviceaccount:
  name: stationbot
