appVersion: __TAG__

deployment:
  name: stationbot
  image: ghcr.io/preparingforexams/station-bot
  imagePullPolicy: IfNotPresent
  labels:
    app: stationbot
  limits:
    cpu: 100m
    memory: 265Mi
  updateStrategy: Recreate

resources:
  limits:
    cpu: "1000m"
    memory: 512Mi
  requests:
    cpu: "500m"
    memory: 512Mi

secret:
  name: station-bot
