apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
    type: {{ .Values.deployment.updateStrategy }}
  selector:
    matchLabels:
      {{- range $k, $v := .Values.deployment.labels }}
      {{ $k }}: {{ $v }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range $k, $v := .Values.deployment.labels }}
        {{ $k }}: {{ $v }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceaccount.name }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.deployment.image }}:{{ .Values.appVersion }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
            - configMapRef:
                name: {{ .Values.configmap.name }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          resources:
            limits:
              cpu: {{ .Values.deployment.limits.cpu }}
              memory: {{ .Values.deployment.limits.memory }}
