---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: station-bot
spec:
  secretStoreRef:
    name: doppler-prep
    kind: ClusterSecretStore
  target:
    name: station-bot
  data:
    - remoteRef:
        key: STATION_TELEGRAM_TOKEN
      secretKey: BOT_TOKEN
