apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
data:
  BOT_TOKEN: "{{ .Values.secret.botToken }}"
  DB_CLIENT_ID: "{{ .Values.configmap.db.clientId }}"
  DB_CLIENT_SECRET: "{{ .Values.configmap.db.clientSecret }}"
