
STATIONS = [
    {
        "name": "Boren-Lindaunis Schleibrücke Nord".strip(),
        "name_link": "https://de.wikipedia.org/wiki/Lindaunisbr%C3%BCcke",
        "type": "Haltepunkt",
        "tracks": None,
        "town": "Lindau",
        "town_link": "https://de.wikipedia.org/wiki/Lindau_(Boren)",
        "district": "",
        "opening": "",
        "transport_association": "",
        "category": "",
        "stop_type": "Regionalverkehrshalt",
        "routes": "[Kiel-Flensburg](https://de.wikipedia.org/wiki/Bahnstrecke_Kiel%E2%80%93Flensburg)",
        "notes": "",
        "done_timestamp": None,
    },
    {
        "name": "Rieseby Schleibrücke Süd".strip(),
        "name_link": "https://de.wikipedia.org/wiki/Lindaunisbr%C3%BCcke",
        "type": "Haltepunkt",
        "tracks": None,
        "town": "Lindau",
        "town_link": "https://de.wikipedia.org/wiki/Lindau_(Boren)",
        "district": "",
        "opening": "",
        "transport_association": "",
        "category": "",
        "stop_type": "Regionalverkehrshalt",
        "routes": "[Kiel-Flensburg](https://de.wikipedia.org/wiki/Bahnstrecke_Kiel%E2%80%93Flensburg)",
        "notes": "",
        "done_timestamp": None,
    },
    {
        "name": "Lübeck-Moisling".strip(),
        "name_link": "https://de.wikipedia.org/wiki/L%C3%BCbeck-Moisling",
        "type": "Haltepunkt",
        "tracks": 2,
        "town": "Lübeck",
        "town_link": "https://de.wikipedia.org/wiki/L%C3%BCbeck",
        "district": "HL",
        "opening": "22.12.2023",
        "transport_association": "HVV",
        "category": "",
        "stop_type": "Regionalverkehrshalt",
        "routes": "[Lübeck–Hamburg](https://de.wikipedia.org/wiki/Bahnstrecke_L%C3%BCbeck%E2%80%93Hamburg)",
        "notes": "",
        "done_timestamp": None,
    },
]
