apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  CONFIGMAP_NAME: "{{ .Values.configmap.state.name }}"
  CONFIGMAP_NAMESPACE: {{ .Values.namespace }}"
