from bot.actions.stations import StationType

STATIONS = [
    {
        "name": "Boren-Lindaunis Schleibrücke Nord".strip(),
        "name_link": " ",
        "type": "BHF",
        "tracks": None,
        "town": "",
        "town_link": "",
        "district": "",
        "opening": "",
        "transport_association": "",
        "category": "",
        "stop_type": "",
        "routes": "",
        "notes": "",
        "done_timestamp": None,
    },
    {
        "name": "Rieseby Schleibrücke Süd".strip(),
        "name_link": " ",
        "type": "BHF",
        "tracks": None,
        "town": "",
        "town_link": "",
        "district": "",
        "opening": "",
        "transport_association": "",
        "category": "",
        "stop_type": "",
        "routes": "",
        "notes": "",
        "done_timestamp": None,
    },
    {
        "name": "Lübeck-Moisling".strip(),
        "name_link": " ",
        "type": "BHF",
        "tracks": None,
        "town": "",
        "town_link": "",
        "district": "",
        "opening": "",
        "transport_association": "",
        "category": "",
        "stop_type": "",
        "routes": "",
        "notes": "",
        "done_timestamp": None,
    }
]
