name: Main
on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  validate-renovate-config:
    uses: BlindfoldedSurgery/renovate-config/.github/workflows/validate.yml@main

#  lint:
#    uses: BlindfoldedSurgery/actions-python/.github/workflows/lint.yml@v1
#    with:
#      python-version: '3.12'

  test:
    uses: BlindfoldedSurgery/actions-python/.github/workflows/test.yml@v1
    with:
      python-version: '3.12'

  build-container-image:
    needs:
      - test
    uses: BlindfoldedSurgery/actions-container/.github/workflows/build-image-docker.yml@v3
    with:
      platform: "linux/arm64"
      push-image: ${{ github.ref_name == github.event.repository.default_branch }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-container-image
    steps:
      - uses: actions/checkout@v4
      - run: |
          git fetch origin argocd
          git switch argocd
          git rebase main
          git push origin argocd
